// Generated by https://quicktype.io

declare interface WebpackConfig {
    mode:    string;
    entry:   Entry;
    output:  Output;
    module:  Module;
    resolve: Resolve;
    plugins: any[];
    devtool:string;
    devServer: object;
}

interface Entry {
    app: string;
}

interface Module {
    rules: Rule[];
}

interface Rule {
    test:     RegExp;
    use:      Array<PurpleUse | string> | FluffyUse;
    exclude?: RegExp;
}

interface PurpleUse {
    loader:  string;
    options: PurpleOptions;
}

interface PurpleOptions {
    sourceMap: boolean;
}

interface FluffyUse {
    loader:  string;
    options: FluffyOptions;
}

interface FluffyOptions {
    transpileOnly: boolean;
}

interface Output {
    path:       string;
    filename:   string;
    publicPath: string;
}

interface Resolve {
    extensions: string[];
    alias: object
}
