/* eslint-disable */
// Generated by component library do not modify
import TextField from './TextField.js';

function dispatchEvent(data) {
  if (typeof window !== 'undefined') {
    const BluekitEvent = require('react-bluekit/lib/libraries/BluekitEvent');
    document.dispatchEvent(new BluekitEvent('functionTriggered', data));
  } else
    console.log('Bluekit received function triggered', data)
}

export default {
  TextField: {
    name: 'TextField',
    menu: 'TextField',
    file: './TextField.js',
    component: TextField,
    componentName: 'TextField',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
}
